package com.hibconfig;
// Generated Jul 12, 2016 10:03:55 AM by Hibernate Tools 4.3.1



/**
 * Artist generated by hbm2java
 */
public class Artist  implements java.io.Serializable {


     private Integer id;
     private Integer exibitionId;
     private String photo;
     private String name;
     private String contact;
     private String address;
     private String gender;
     private String dob;
     private String summary;
     private String facebook;
     private String twitter;
     private String google;
     private String email;
     private String qualification;
     private String award;
     private String solo;
     private String groupShow;
     private String collection;

    public Artist() {
    }

    public Artist(Integer exibitionId, String photo, String name, String contact, String address, String gender, String dob, String summary, String facebook, String twitter, String google, String email, String qualification, String award, String solo, String groupShow, String collection) {
       this.exibitionId = exibitionId;
       this.photo = photo;
       this.name = name;
       this.contact = contact;
       this.address = address;
       this.gender = gender;
       this.dob = dob;
       this.summary = summary;
       this.facebook = facebook;
       this.twitter = twitter;
       this.google = google;
       this.email = email;
       this.qualification = qualification;
       this.award = award;
       this.solo = solo;
       this.groupShow = groupShow;
       this.collection = collection;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getExibitionId() {
        return this.exibitionId;
    }
    
    public void setExibitionId(Integer exibitionId) {
        this.exibitionId = exibitionId;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getGoogle() {
        return this.google;
    }
    
    public void setGoogle(String google) {
        this.google = google;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public String getAward() {
        return this.award;
    }
    
    public void setAward(String award) {
        this.award = award;
    }
    public String getSolo() {
        return this.solo;
    }
    
    public void setSolo(String solo) {
        this.solo = solo;
    }
    public String getGroupShow() {
        return this.groupShow;
    }
    
    public void setGroupShow(String groupShow) {
        this.groupShow = groupShow;
    }
    public String getCollection() {
        return this.collection;
    }
    
    public void setCollection(String collection) {
        this.collection = collection;
    }




}


