package com.hibconfig;
// Generated Jul 12, 2016 10:03:55 AM by Hibernate Tools 4.3.1



/**
 * Buyinguserlist generated by hbm2java
 */
public class Buyinguserlist  implements java.io.Serializable {


     private Integer id;
     private Integer productId;
     private String name;
     private String mobile;
     private String email;
     private String address;
     private String city;
     private String stateName;
     private String pincode;
     private String landmark;

    public Buyinguserlist() {
    }

    public Buyinguserlist(Integer productId, String name, String mobile, String email, String address, String city, String stateName, String pincode, String landmark) {
       this.productId = productId;
       this.name = name;
       this.mobile = mobile;
       this.email = email;
       this.address = address;
       this.city = city;
       this.stateName = stateName;
       this.pincode = pincode;
       this.landmark = landmark;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public String getLandmark() {
        return this.landmark;
    }
    
    public void setLandmark(String landmark) {
        this.landmark = landmark;
    }




}


