package com.hibconfig;
// Generated Jul 12, 2016 10:03:55 AM by Hibernate Tools 4.3.1



/**
 * Exibiton generated by hbm2java
 */
public class Exibiton  implements java.io.Serializable {


     private Integer id;

    public Exibiton() {
    }

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }




}


