package com.hibconfig;
// Generated Jul 12, 2016 10:03:55 AM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private Integer artistId;
     private String name;
     private String sizeP;
     private String medium;
     private String conditionP;
     private String soldBy;
     private String price;
     private String featureImg;
     private String cartImg;

    public Product() {
    }

    public Product(Integer artistId, String name, String sizeP, String medium, String conditionP, String soldBy, String price, String featureImg, String cartImg) {
       this.artistId = artistId;
       this.name = name;
       this.sizeP = sizeP;
       this.medium = medium;
       this.conditionP = conditionP;
       this.soldBy = soldBy;
       this.price = price;
       this.featureImg = featureImg;
       this.cartImg = cartImg;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(Integer artistId) {
        this.artistId = artistId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSizeP() {
        return this.sizeP;
    }
    
    public void setSizeP(String sizeP) {
        this.sizeP = sizeP;
    }
    public String getMedium() {
        return this.medium;
    }
    
    public void setMedium(String medium) {
        this.medium = medium;
    }
    public String getConditionP() {
        return this.conditionP;
    }
    
    public void setConditionP(String conditionP) {
        this.conditionP = conditionP;
    }
    public String getSoldBy() {
        return this.soldBy;
    }
    
    public void setSoldBy(String soldBy) {
        this.soldBy = soldBy;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getFeatureImg() {
        return this.featureImg;
    }
    
    public void setFeatureImg(String featureImg) {
        this.featureImg = featureImg;
    }
    public String getCartImg() {
        return this.cartImg;
    }
    
    public void setCartImg(String cartImg) {
        this.cartImg = cartImg;
    }




}


